'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('web/console/tenant/dashboard.html','utf8');
const js=fs.readFileSync('web/console/tenant/app.js','utf8');
const api=fs.readFileSync('apps/control-api/src/commercial_tenant_api.rs','utf8');
const sql=fs.readFileSync('deploy/db/migrations/0040_pppoe_execution_safety_state.sql','utf8');
assert(html.includes('Provisioning Officers create audited CSV dry-runs'));
assert(html.includes('Security Admins independently approve or reject'));
assert(html.includes('distinct current System Admin'));
assert(html.includes('ambiguous timeouts require reconciliation'));
assert(js.includes('can_arm_pppoe_plans'));
assert(js.includes('Arm reviewed execution'));
assert(js.includes('ARM_REVIEWED_PPPOE_EXECUTION'));
assert(js.includes('generic RouterOS adapter disabled'));
assert(js.includes('physical_execution_adapter_enabled'));
assert(api.includes('authenticate_high_risk'));
assert(api.includes('if !can_arm'));
assert(api.includes('arm_pppoe_batch_execution'));
assert(sql.includes("'system_admin'"));
assert(sql.includes('pppoe_execution_arm_capability'));
assert(sql.includes('unknown_reconcile_required'));
assert(sql.includes('CLAIM_EXPIRED_TO_UNKNOWN'));
assert(sql.includes('physical_execution_adapter_enabled'));
assert(!sql.includes('routeros_command('));
assert(!sql.includes('execute_router_command('));
console.log('R1010_PPPOE_THREE_ROLE_ARM_LEASE_RECONCILE_UI_API_CONTRACT=PASS');
