'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('web/console/tenant/dashboard.html','utf8');
const js=fs.readFileSync('web/console/tenant/app.js','utf8');
const tenant=fs.readFileSync('apps/control-api/src/commercial_tenant_api.rs','utf8');
const domain=fs.readFileSync('apps/control-api/src/tenant_domain.rs','utf8');
const platform=fs.readFileSync('apps/control-api/src/platform_owner_api.rs','utf8');
assert(html.includes('domain-dns-guide" hidden'));
assert(html.includes('The IPAT main brand domain is not required'));
assert(js.includes("+'/dns'"));
assert(js.includes("safe_to_point_now"));
assert(js.includes("guide.verification_value"));
assert(js.includes('textContent=String(value)'));
assert(!js.includes("$('domain-dns-records').innerHTML"));
assert(tenant.includes('list_tenant_domains_for_member($1,$2,$3::uuid)'));
assert(tenant.includes('actor(&s.db, &headers, false)'));
assert(tenant.includes('saved_customer_dns_guidance'));
assert(domain.includes('activation_requires_verification'));
assert(domain.includes('VERIFIED_AND_INGRESS_REVIEWED'));
assert(platform.includes('eligible_temporary_ipv4'));
assert(platform.includes('IPAT_R982_IP_SAN_TLS_REVIEWED'));
console.log('R982_TEMPORARY_IPV4_CUSTOMER_DOMAIN_DNS_UI_CONTRACT=PASS');
