'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('web/console/tenant/dashboard.html','utf8');
const js=fs.readFileSync('web/console/tenant/app.js','utf8');
const api=fs.readFileSync('apps/control-api/src/commercial_tenant_api.rs','utf8');
const sql=fs.readFileSync('deploy/db/migrations/0035_subscriber360_diagnostics.sql','utf8');
assert(html.includes('id="subscriber-manage" hidden'));
assert(html.includes('declarations are not considered verified'));
assert(html.includes('data-page="diagnostics" hidden'));
assert(js.includes('canReadSubscribers'));
assert(js.includes('canManageSubscribers'));
assert(js.includes("topology_state==='verified'"));
assert(js.includes("remediation: '+r.remediation_permitted"));
assert(!js.includes("subscriber-rows').innerHTML"));
assert(api.includes('subscriber_schema_ready'));
assert(api.includes('"topology_verified":topology_verified'));
assert(api.includes('"remediation_permitted":result.remediation_permitted'));
assert(sql.includes('ipat_topology_verify_exec'));
assert(sql.includes('record_subscriber_topology_verification'));
assert(sql.includes("topology_state='declared'"));
assert(sql.includes('can_read_subscriber_scope'));
assert(js.includes("if(state.canReadSubscribers){$('nav-subscribers').hidden=false;$('nav-diagnostics').hidden=false}"));
assert(js.includes("$('subscriber-manage').hidden=!state.canManageSubscribers"));
assert(sql.includes('topology_declared_at'));
assert(sql.includes('p_observed_at>=s.topology_declared_at'));
console.log('R1005_SUBSCRIBER360_DIAGNOSTICS_UI_SOURCE=PASS');
